# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('answer_id', models.AutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('asker', models.CharField(default=None, max_length=30, verbose_name='asker')),
                ('answer_by', models.CharField(default='User', max_length=100, verbose_name='answer by')),
                ('answer', models.CharField(default=None, max_length=800, verbose_name='answer')),
                ('up_vote', models.IntegerField(default=0, verbose_name='upvote')),
                ('down_vote', models.IntegerField(default=0, verbose_name='downvote')),
                ('all_votings', models.IntegerField(default=0, verbose_name='voters')),
                ('weekday', models.IntegerField(default=1, verbose_name='week day')),
                ('dayOfWeek', models.IntegerField(default=1, verbose_name='day Of Week')),
                ('comment', models.CharField(default='no comment', max_length=200, verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='ask_question',
            fields=[
                ('asker', models.CharField(default='User', max_length=100, verbose_name='Asker')),
                ('question_id', models.AutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('question_title', models.CharField(default=None, max_length=150, verbose_name='question title')),
                ('question', models.CharField(default=None, max_length=1000, verbose_name='question')),
                ('specialization', models.CharField(default=None, max_length=50, verbose_name='specialization')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('upvote', models.IntegerField(default=0, verbose_name='upvote')),
                ('downvote', models.IntegerField(default=0, verbose_name='downvote')),
                ('all_votings', models.IntegerField(default=0, verbose_name='Voters')),
                ('weekday', models.IntegerField(default=0, verbose_name='week day')),
                ('dayOfWeek', models.IntegerField(default=1, verbose_name='day Of Week')),
            ],
        ),
        migrations.CreateModel(
            name='libarary',
            fields=[
                ('uploader', models.CharField(default='User', max_length=100, verbose_name='Upload by')),
                ('file_name', models.CharField(default='File', max_length=200, verbose_name='File Name')),
                ('file_id', models.AutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to=b'/home/wdaud/python_World/Alzitoona/media/', verbose_name='file')),
                ('specialization', models.CharField(default='general', max_length=50, verbose_name='specialization')),
                ('description', models.CharField(default='no description', max_length=200, verbose_name='description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('weekday', models.IntegerField(default=0, verbose_name='week day')),
                ('dayOfWeek', models.IntegerField(default=1, verbose_name='day Of Week')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.ask_question'),
        ),
    ]
