# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(default='user', max_length=100, verbose_name='nick name')),
                ('specialization', models.CharField(max_length=100, verbose_name='specialization')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('photo_name', models.CharField(default='', max_length=100, verbose_name='photo name')),
                ('photo', models.FileField(default=None, upload_to=b'/home/wdaud/python_World/Alzitoona/media/')),
                ('upvote', models.IntegerField(default=0, verbose_name='up vote')),
                ('downvote', models.IntegerField(default=0, verbose_name='down vote')),
                ('total_votes', models.IntegerField(default=0, verbose_name='total votes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='user', max_length=100)),
                ('index', models.CharField(max_length=20, unique=True, verbose_name='index')),
                ('specialization', models.CharField(max_length=100, verbose_name='specialization')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('age', models.CharField(max_length=5, verbose_name='age')),
                ('related_interest', models.CharField(max_length=20, verbose_name='Related Interest')),
                ('photo_name', models.CharField(default='', max_length=100, verbose_name='photo name')),
                ('photo', models.FileField(default=None, upload_to=b'/home/wdaud/python_World/Alzitoona/media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
